language: python
dist: xenial
# addons:
#     postgresql: "10"
#     apt:
#         packages:
#             - "postgresql-10-postgis-2.4"
python:
  - "3.7"
env:
  - BOTO_CONFIG=/dev/null
before_install:
  - sudo apt-get install -y gdal-bin
  - git clone https://github.com/mapbox/tippecanoe.git; cd tippecanoe; make -j; sudo make install; cd ..
install:
  - pip install poetry
  - poetry install
  - npm ci
  - npm run build
# before_script:
#     - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
#     - psql -c "CREATE DATABASE test;" -U postgres
#     - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
jobs:
  include:
    - script: poetry run pytest --ds=openprecincts_web.test_settings -v --nomigrations
      name: "Run Tests"
    - script: poetry run flake8
      name: "flake8"
notifications:
    email:
        - jpturk@princeton.edu
