language: python
dist: xenial
# addons:
#     postgresql: "10"
#     apt:
#         packages:
#             - "postgresql-10-postgis-2.4"
python:
  - "3.7"
env:
  - BOTO_CONFIG=/dev/null
before_install:
  - sudo apt-get install -y gdal-bin
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv graph
  - npm ci
  - npm run build
# before_script:
#     - psql -c "CREATE USER test with PASSWORD 'test' CREATEDB SUPERUSER;" -U postgres
#     - psql -c "CREATE DATABASE test;" -U postgres
#     - psql -c "CREATE EXTENSION postgis;" -U postgres -d test
jobs:
  include:
    - script: pipenv run pytest --ds=openprecincts_web.test_settings --reuse-db -v
      name: "Run Tests"
    - script: pipenv run flake8
      name: "flake8"
notifications:
    email:
        - jpturk@princeton.edu
