version: "3.1"

services:
  rabbitmq:
    image: "rabbitmq:3.7"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
  postgres:
    image: "postgres:10"
    hostname: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: openprecincts
      POSTGRES_DB: openprecincts
