version: "3.1"

services:
  rabbitmq:
    image: "rabbitmq:3.7"
    hostname: "rabbitmq"
    ports:
      - "5672:5672"
  db:
    image: "postgres:10"
    hostname: "db"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: testpassword
      POSTGRES_USER: openprecincts
      POSTGRES_DB: openprecincts
  webpack:
    build: .
    command: npm run start
    volumes:
      - .:/code
  django:
    build: .
    command: /venv/bin/pipenv run ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
