# Generated by Django 2.1.5 on 2019-02-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=20)),
                ('wikipedia_url', models.URLField()),
                ('official_url', models.URLField()),
                ('ocd_id', models.CharField(max_length=200, unique=True)),
                ('census_geoid', models.CharField(max_length=5, unique=True)),
            ],
        ),
    ]
