# Generated by Django 2.1.7 on 2019-02-15 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contacted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_log_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wikipedia_url', models.URLField()),
                ('official_url', models.URLField()),
                ('ocd_id', models.CharField(max_length=200, unique=True)),
                ('census_geoid', models.CharField(max_length=5, unique=True)),
            ],
            options={
                'verbose_name_plural': 'localities',
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('title', models.CharField(choices=[('Ms.', 'Ms.'), ('Mr.', 'Mr.'), ('Dr.', 'Dr.'), ('Hon.', 'Hon.'), ('', '-none-')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('job_title', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_officials', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='officials', to='core.Locality')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('abbreviation', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('census_geoid', models.CharField(max_length=2, unique=True)),
                ('precinct_plan', models.PositiveIntegerField(choices=[(0, 'UNKNOWN'), (1, 'COUNTY_BY_COUNTY'), (2, 'EXTERNAL_PARTNER'), (3, 'STATEWIDE_ORG')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='locality',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='localities', to='core.State'),
        ),
        migrations.AddField(
            model_name='contactlog',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact_log_entries', to='core.Official'),
        ),
    ]
