# Generated by Django 2.1.5 on 2019-02-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_file_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file_type',
        ),
        migrations.AddField(
            model_name='file',
            name='size',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
