# Generated by Django 2.2.1 on 2019-05-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_electionresult_county_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='task_digitization',
        ),
        migrations.RemoveField(
            model_name='state',
            name='task_verification',
        ),
        migrations.AddField(
            model_name='state',
            name='status',
            field=models.CharField(choices=[('unknown', 'unknown'), ('collection', 'collection'), ('cleaning', 'cleaning'), ('available', 'available')], default='unknown', max_length=10),
        ),
    ]
