# Generated by Django 2.2.1 on 2019-05-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0008_auto_20190517_1715")]

    operations = [
        migrations.RemoveField(model_name="state", name="task_collect"),
        migrations.RemoveField(model_name="state", name="task_contact"),
        migrations.RemoveField(model_name="state", name="task_files"),
        migrations.RemoveField(model_name="state", name="task_published"),
        migrations.AlterField(
            model_name="state",
            name="status",
            field=models.CharField(
                choices=[
                    ("unknown", "unknown"),
                    ("collection", "collection"),
                    ("cleaning", "cleaning"),
                    ("prior-year", "prior-year"),
                    ("available", "available"),
                ],
                default="unknown",
                max_length=10,
            ),
        ),
    ]
