# Generated by Django 2.2.4 on 2019-08-20 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190521_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='status',
            field=models.CharField(choices=[('need-to-collect', 'need-to-collect'), ('geography', 'geography'), ('election-data-linked', 'election-data-linked'), ('census-data-linked', 'census-data-linked'), ('validated', 'validated')], default='need-to-collect', max_length=30),
        ),
    ]
