# Generated by Django 2.2.4 on 2019-09-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20190820_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='show_crowdsourcing_tools',
            field=models.BooleanField(default=False),
        ),
    ]
