# Generated by Django 2.2.4 on 2019-09-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_statewideelection_election_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name']},
        ),
    ]
