# Generated by Django 2.2.10 on 2020-02-27 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190924_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateCycle',
        ),
    ]
