# Generated by Django 2.2.4 on 2020-01-30 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20190924_1757'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StateCycle',
        ),
    ]
