# Generated by Django 2.2.10 on 2020-03-16 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_statecycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statewideelection',
            name='office_type',
            field=models.CharField(choices=[('P', 'President'), ('G', 'Governor'), ('S', 'Senate'), ('H', 'House of Representatives'), ('SL', 'State Lower Chamber'), ('SU', 'State Senate'), ('AG', 'Attorney General'), ('ST', 'Secretary of State'), ('TR', 'Treasurer'), ('LG', 'Lieutenant Governor')], default='P', max_length=2),
        ),
    ]
