# Generated by Django 2.2.10 on 2020-03-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200316_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statewideelection',
            name='dem_property',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statewideelection',
            name='rep_property',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
