# Generated by Django 2.2.10 on 2020-05-27 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200317_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='statewideelection',
            name='mbtile_name',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
