# Generated by Django 2.2.10 on 2020-04-02 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200317_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('PGP', 'Princeton Gerrymandering Project'), ('VEST', 'Voting and Election Science Team'), ('MGGG', 'Metric Geometry and Gerrymandering Group')], default='PGP', max_length=4)),
                ('year', models.CharField(default='2016', max_length=4)),
                ('all_precincts_have_a_geometry', models.BooleanField(default=False)),
                ('can_use_maup', models.BooleanField(default=False)),
                ('can_use_gerrychain', models.BooleanField(default=False)),
                ('n_votes_democrat', models.IntegerField()),
                ('n_votes_republican', models.IntegerField()),
                ('statewide_accuracy', models.FloatField()),
                ('county_variance', models.FloatField()),
                ('used_maup_for_county_assignment', models.BooleanField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.State')),
            ],
        ),
    ]
