# Generated by Django 2.2.10 on 2020-04-02 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_statereport'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('census_geoid', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('n_votes_democrat', models.IntegerField()),
                ('n_votes_republican', models.IntegerField()),
                ('countywide_accuracy', models.FloatField()),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.StateReport')),
            ],
        ),
    ]
