# Generated by Django 2.1.7 on 2019-03-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_emailmessage_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessageInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_email', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField()),
                ('body_text', models.TextField()),
                ('reply_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.EmailMessageInstance')),
            ],
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='officials',
            field=models.ManyToManyField(related_name='messages', through='contact.EmailMessageInstance', to='contact.Official'),
        ),
        migrations.AddField(
            model_name='emailmessageinstance',
            name='email_message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.EmailMessage'),
        ),
        migrations.AddField(
            model_name='emailmessageinstance',
            name='official',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.Official'),
        ),
    ]
