# Generated by Django 2.1.7 on 2019-03-15 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contact", "0006_auto_20190315_1935"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailmessage",
            name="approved_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="emailmessage",
            name="approved_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approved_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
