# Generated by Django 2.1.7 on 2019-03-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("files", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="file", name="source_url", field=models.URLField(blank=True)
        )
    ]
