# Generated by Django 2.2 on 2019-04-11 21:09

from django.db import migrations, models
import django.db.models.deletion


def forwards_func(apps, schema_editor):
    # attach all files .cycle parameter
    File = apps.get_model("files", "File")
    db_alias = schema_editor.connection.alias
    for f in File.objects.all():
        f.cycle = f.locality.state.cycles.order_by("-year")[0]
        f.save()


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_auto_20190411_1927"),
        ("files", "0002_file_source_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="cycle",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="files",
                to="core.StateCycle",
            ),
        ),
        migrations.RunPython(forwards_func),
    ]
