# Generated by Django 2.2 on 2019-04-11 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='core.StateCycle'),
        ),
    ]
