# Generated by Django 2.2.1 on 2019-05-17 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_auto_20190422_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='official',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='contact.Official'),
        ),
    ]
