# Generated by Django 2.2.1 on 2019-05-24 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("files", "0008_auto_20190517_1644")]

    operations = [
        migrations.RemoveField(model_name="file", name="from_transformation"),
        migrations.DeleteModel(name="Transformation"),
    ]
