# Generated by Django 2.2.1 on 2019-05-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("files", "0009_auto_20190524_1850")]

    operations = [
        migrations.AddField(
            model_name="file",
            name="from_transformation",
            field=models.CharField(blank=True, max_length=100),
        )
    ]
