# Generated by Django 2.2.4 on 2020-02-18 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0011_remove_file_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
