# Generated by Django 2.2.4 on 2020-02-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_statecycle'),
        ('files', '0011_remove_file_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='statewide_elections',
            field=models.ManyToManyField(related_name='files', to='core.StatewideElection'),
        ),
    ]
