# Generated by Django 2.2.4 on 2020-02-18 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_file_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='year',
            new_name='election_year',
        ),
    ]
